### ISSUE TITLE
No SQL File/Install Script included the Library

### ISSUE THREAD

**Issue by wilforlan** [HarunRRayhan/oophplr#1]
I think an Install Script should be included in the file to handle database migration with test data. Its not so easy trying to guess what the table names should be and of what data type the columns should be

**Comment by HarunRRayhan** [comment]
I'll include soon. It's just for practice, modifying soon to implement on other projects :)

**Comment by wilforlan** [comment]
Okay @HarunRRayhan I am Integrating it with a Custom Framework I think its good enough to Integrate
Thanks

**Comment by HarunRRayhan** [comment]
@wilforlan DB dump file added.
Please check now
